from fastapi import APIRouter

from app.api.v1 import agents, auth, communication, companies, compute_api, culture, dashboard, discovery_api, economy, execution, evolution, federation, genesis_api, governance, identity, management_api, marketplace, meta_api, planetary_api, platform_api, reality_api, reasoning, research, resources, simulation, tasks, technology, temporal_api, wallets, world

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(dashboard.router)
api_router.include_router(agents.router)
api_router.include_router(identity.router)
api_router.include_router(reasoning.router)
api_router.include_router(resources.router)
api_router.include_router(tasks.router)
api_router.include_router(marketplace.router)
api_router.include_router(execution.router)
api_router.include_router(wallets.router)
api_router.include_router(companies.router)
api_router.include_router(simulation.router)
api_router.include_router(communication.router)
api_router.include_router(economy.router)
api_router.include_router(governance.router)
api_router.include_router(evolution.router)
api_router.include_router(research.router)
api_router.include_router(world.router)
api_router.include_router(federation.router)
api_router.include_router(culture.router)
api_router.include_router(technology.router)
api_router.include_router(planetary_api.router)
api_router.include_router(temporal_api.router)
api_router.include_router(meta_api.router)
api_router.include_router(platform_api.router)
api_router.include_router(reality_api.router)
api_router.include_router(management_api.router)
api_router.include_router(genesis_api.router)
api_router.include_router(compute_api.router)
api_router.include_router(discovery_api.router)
